import numpy as np
from matplotlib.colors import to_hex, to_rgb

from .alg import generate, oklch_to_srgb, srgb_to_oklch


def create_palette(
    dark_L=0.4,
    bright_L=0.55,
    dark_shifts=None,
    bright_shifts=None,
    hex_extra_colors=("#db7201", "#dca401", "#00ae0d"),
    hex_greys=None,
):
    """
    Create a color palette.

    Colors are generated by alg.generate. By default, the dark blue
    color is shifted by -0.05, while all other colors are unshifted.

    If no greys are provided, create_greys(bright_L) generates them.

    Extra colors are simply appended to the palette.
    """
    if hex_greys is None:
        hex_greys = create_greys(dark_L, bright_L)
    if dark_shifts is None:
        dark_shifts = 5 * [0]
        dark_shifts[2] = -0.05

    colors = [
        oklch_to_hex(*c)
        for c in generate(dark_L, shifts=dark_shifts)
        + generate(bright_L, n_magenta=2, shifts=bright_shifts)
    ]
    return np.concatenate(
        (hex_greys, np.array(colors), list(hex_extra_colors))
    )


def create_greys(
    dark_grey_L,
    bright_grey_L,
    subtle_grey_L=None,
    hex_black="#000000",
    hex_crust="#deddda",
    hex_mantle="#f6f5f4",
    hex_base="#ffffff",
):
    """
    Create grey shades.

    One dark grey is interpolated between black and dark grey.
    Four light greys are interpolated between subtle grey and crust.

    If no subtle_grey_L is given, it is set to `bright_grey_L + 0.1`.

    The four given shades are appended to the list of greys.
    """
    if subtle_grey_L is None:
        subtle_grey_L = bright_grey_L + 0.1
    black_L = srgb_to_oklch(*to_rgb(hex_black))[0]
    crust_L = srgb_to_oklch(*to_rgb(hex_crust))[0]

    dark_grays_L = list(np.linspace(black_L, dark_grey_L, 3)[1:])
    light_grays_L = list(np.linspace(subtle_grey_L, crust_L, 6)[:-1])
    return np.array(
        [hex_black]
        + [
            oklch_to_hex(L, 0, 0)
            for L in dark_grays_L + [bright_grey_L] + light_grays_L
        ]
        + [hex_crust, hex_mantle, hex_base]
    )


def oklch_to_hex(L, c, h):
    """
    Return sRGB hex value corresponding to OKLCH L, c, h.
    """
    return to_hex(oklch_to_srgb(L, c, h))
